//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mkt_Calculation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData1 {
            get {
                return ((double)(this["CelesiusData1"]));
            }
            set {
                this["CelesiusData1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData2 {
            get {
                return ((double)(this["CelesiusData2"]));
            }
            set {
                this["CelesiusData2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData3 {
            get {
                return ((double)(this["CelesiusData3"]));
            }
            set {
                this["CelesiusData3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData4 {
            get {
                return ((double)(this["CelesiusData4"]));
            }
            set {
                this["CelesiusData4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData5 {
            get {
                return ((double)(this["CelesiusData5"]));
            }
            set {
                this["CelesiusData5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData6 {
            get {
                return ((double)(this["CelesiusData6"]));
            }
            set {
                this["CelesiusData6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData7 {
            get {
                return ((double)(this["CelesiusData7"]));
            }
            set {
                this["CelesiusData7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData8 {
            get {
                return ((double)(this["CelesiusData8"]));
            }
            set {
                this["CelesiusData8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData9 {
            get {
                return ((double)(this["CelesiusData9"]));
            }
            set {
                this["CelesiusData9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData10 {
            get {
                return ((double)(this["CelesiusData10"]));
            }
            set {
                this["CelesiusData10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData11 {
            get {
                return ((double)(this["CelesiusData11"]));
            }
            set {
                this["CelesiusData11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData12 {
            get {
                return ((double)(this["CelesiusData12"]));
            }
            set {
                this["CelesiusData12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData13 {
            get {
                return ((double)(this["CelesiusData13"]));
            }
            set {
                this["CelesiusData13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData14 {
            get {
                return ((double)(this["CelesiusData14"]));
            }
            set {
                this["CelesiusData14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData15 {
            get {
                return ((double)(this["CelesiusData15"]));
            }
            set {
                this["CelesiusData15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData16 {
            get {
                return ((double)(this["CelesiusData16"]));
            }
            set {
                this["CelesiusData16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData17 {
            get {
                return ((double)(this["CelesiusData17"]));
            }
            set {
                this["CelesiusData17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData18 {
            get {
                return ((double)(this["CelesiusData18"]));
            }
            set {
                this["CelesiusData18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData19 {
            get {
                return ((double)(this["CelesiusData19"]));
            }
            set {
                this["CelesiusData19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData20 {
            get {
                return ((double)(this["CelesiusData20"]));
            }
            set {
                this["CelesiusData20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData21 {
            get {
                return ((double)(this["CelesiusData21"]));
            }
            set {
                this["CelesiusData21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData22 {
            get {
                return ((double)(this["CelesiusData22"]));
            }
            set {
                this["CelesiusData22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData23 {
            get {
                return ((double)(this["CelesiusData23"]));
            }
            set {
                this["CelesiusData23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double CelesiusData24 {
            get {
                return ((double)(this["CelesiusData24"]));
            }
            set {
                this["CelesiusData24"] = value;
            }
        }
    }
}
